### ISSUE TITLE
template: Unclear deprecated-template filenames

### ISSUE THREAD

**Issue by wking** [spdx/license-list-data#17]
We currently have both `template/LGPL-3.0.template.txt` and `template/deprecated_LGPL-3.0.template.txt` and they don't match.  The Git history is:

```console
$ git log --oneline --decorate --stat template/*LGPL-3.0.template.txt
5909af5 Release candidate for the 3.0 version of the license list
 template/deprecated_LGPL-3.0.template.txt | 45 +++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 45 insertions(+)
199db90 Renaming files in the txt and template directories per suggestion by @sschuberth
 template/LGPL-3.0.template.txt | 71 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 71 insertions(+)
```

199db90 is from way back:

```console
$ git describe --contains 199db90
v2.4~1
```

I expect 5909af5 or another commit in the run-up to 3.0 intended to remove `LGPL-3.0.template.txt` now that we have a `deprecated_LGPL-3.0.template.txt`.  But I couldn't find docs for the filenames.

Personally, I'd rather punt deprecated-ness to other locations, and keep the `LGPL-3.0` template in `LGPL-3.0.template.txt` even though the license is deprecated.  The point of deprecation is to give folks time to upgrade their usage/tooling, and renaming the template file immediately on deprecation seems like it might break consumers.

**Comment by goneall** [comment]
The extra files were left due to human error while creating the data from the 3.0 release.  Pull request #18 fixes this issue.

@wking thanks for catching this!

In terms of naming, I added the deprecated since in previous versions there was no way to tell if a file was deprecated or not.  Another suggestion was not to include the files at all.

Since most tools consumers will use the JSON or RDF representations, I don't think this will be an issue.  We can re-open this if someone reports a tool that is actually broken by the renaming.

**Comment by goneall** [comment]
Added pull request documenting the use.
