### ISSUE TITLE
Generated v3.3 data

### ISSUE THREAD

**Issue by pombredanne** [spdx/license-list-data#37]
It would be great to also have the data for the v3.3 of the license list https://github.com/spdx/license-list-XML/releases/tag/3.3

**Comment by pombredanne** [comment]
@goneall I think that the only thing missing is a tag, right?

**Comment by goneall** [comment]
@pombredanne Yes - just missing the tag.  I'll add that to the list of steps to publishing a new license list.

**Comment by goneall** [comment]
Just a bit more info - there was a bug in the travis file that automatically updates this repository.  It wasn't updating when only a tag was pushed.  This was fixed with https://github.com/spdx/license-list-XML/commit/63b75027f8618b6ce76b8b0ae911e38022b1f421

Future releases should not have this problem.

I'll go back and manually tag this release.

**Comment by goneall** [comment]
Just tagged the 3.3 release

**Comment by pombredanne** [comment]
Thanks ++ :bowing_man: :heart:
