### ISSUE TITLE
Corrupted URLs

### ISSUE THREAD

**Issue by tastytea** [spdx/license-list-data#42]
Some URLs  have spaces around the s in https. Example: 
https://github.com/spdx/license-list-data/blob/f2abf252d6911e3827dcdb4decbbc0901ae6db66/text/GPL-3.0-only.txt#L5

[List of affected files](https://github.com/spdx/license-list-data/files/2688231/list.txt) (found with `grep -rl 'http s'`)

**Comment by goneall** [comment]
@tastytea thanks for reporting the issue.

It turns out to be an issue with the tool: https://github.com/spdx/LicenseListPublisher/issues/42

It may be a few weeks before it is resolved - it will be difficult to fix this issue without creating other formatting issues.

We could also resolve the specific issues by changing the XML from `http<optional>s</optional>` to an alt tag: `<alt name="https" match="http|https.*">http://....</alt>`

**Comment by mlinksva** [comment]
`alt` also adds surrounding spaces, so potentially larger stretches of text need to be wrapped than would be necessary to capture the optional or alternate text if rendering were not a concern. Example:

https://github.com/spdx/license-list-data/blob/6ee46958b85696cb7e044ca90730c00a5e747ac8/text/CC-BY-4.0.txt#L27

https://github.com/spdx/license-list-XML/blob/5b1f68375508e854a6aa6d1fb87225cb98e50ece/src/CC-BY-4.0.xml#L30

**Comment by goneall** [comment]
This has now been resolved with updates to the license list XML schema, licenseListPublisher and license list XML data.
