### ISSUE TITLE
License.format file into end directories

### ISSUE THREAD

**Issue by idimopoulos** [spdx/license-list-data#48]
Hello, I could not understand from the readme so I had to ask here.

In almost each directory of the generated licenses, there are the files of each license and there is usually a license.format which contains again all the licenses.

For example, in the rdfxml directory, there is the licenses.rdf file which contains 416 entries of licenses and license exceptions. Also, in the same folder, there are 416 separate rdf files that each includes either a license or a license exception.

If someone would want to iterate over all the entries in the folder and import the licenses, he would end up with two times the items. So why it the folder containing the full dump next to the individual files?

**Comment by goneall** [comment]
Good point - there is a request or need for a single file containing all licenses (which is quite large) and a request or need for individual files, so both are important to produce.  

Should we generate the details in a subdirectory "details" like we do with the JSON directory?

I'll create a PR that at least documents the current structure.

**Comment by idimopoulos** [comment]
The json structure indeed is more clear. 
In the end, it is not a real "issue", it is just that different structures in different directories is a bit confusing. 
Even more, different sturctures can even be acceptable if there is at least documentation about it.
Of course, consistent structure design is more appealing.

**Comment by goneall** [comment]
@idimopoulos Agree with the feedback - the code for the different output format was written at different times and I didn't realize they were as different as they are.

I'll close this issue since the documentation has been updated.  If you (or anyone) would like to propose any different file structure for the RDF formats, feel free to open an issue for the [License List Publish](https://github.com/spdx/LicenseListPublisher/issues) - the tool that generates the data for this repo.
