### ISSUE TITLE
License for the repo?

### ISSUE THREAD

**Issue by bnb** [spdx/license-list-data#6]
Is there a list, implied or explicit, for the information in this repository?

**Comment by goneall** [comment]
@jlovejoy Should we add to the README file for the license list data that unless otherwise specified, content is under a creative commons attribution 3.0 license (same as the Linux website terms)?  Open to other suggestions.

**Comment by jeremiah** [comment]
Is the data *really* copyrightable? Not everything needs a copyright, metadata is often cited as an example of something that doesn't need copyright protection and this list of licenses really seems like something that is quite fungible, easily compiled via other means, and offers nothing that might be deemed unique or different.

**Comment by goneall** [comment]
@jeremiah Good point - I was also thinking about the copyrightability as well as the fact some of the licenses have copyrights and terms for the license itself.  I was thinking the "unless otherwise specified" would cover the latter.  I've heard some discussions by lawyers that in non-U.S. jurisdictions, some of this can be covered by a copyright.  Not being a lawyer, I'm not familiar with the specifics - so I thought I'd leave that discussion to the lawyers.  My proposal above was based on the terms for the spdx.org/licenses page which contains the same information.

In any case, it wouldn't be bad to have some statement for anyone who may have a concern about the terms of use for the license compilation whichever decision is made.

**Comment by mongoponzo** [comment]
The various original license files (and text) are copyrighted by the original authors/organizations. Your work on `license-list-data` is copyrighted to you. So basically all the various formats that you are producing on top of the original licenses, because they are "derivative works". For example the [JSON version](https://github.com/spdx/license-list-data/blob/master/json/licenses.json) has information that goes beyond the license text, such as

    {
          "reference": "./CECILL-B.html",
          "isDeprecatedLicenseId": false,
          "detailsUrl": "http://spdx.org/licenses/CECILL-B.json",
          "referenceNumber": "60",
          "name": "CeCILL-B Free Software License Agreement",
          "licenseId": "CECILL-B",
          "seeAlso": [
                "http://www.cecill.info/licences/Licence_CeCILL-B_V1-fr.html"
          ],
          "isOsiApproved": false
    }

What is the license of this metadata, or in other words, everything that you've derived/created on top of the original licenses but that is not the licenses itself? I personally suggest to add a note like "Original licenses are copyright of their respective organizations. Everything else is released in the Public Domain.".

**Disclaimer: IANAL**

**Comment by bnb** [comment]
Realizing this is still open over a year later when it came up in a discussion again – glad I at least brought an interesting discussion to the table! ❤️ 


>In any case, it wouldn't be bad to have some statement for anyone who may have a concern about the terms of use for the license compilation whichever decision is made.

That would be super awesome – I'd like to use this data in a production application that deals with displaying license metadata, but would mostly just know what acceptable use of the data in the repository is! 🙏

**Comment by annania** [comment]
Hello, I am also interested in a license or something describing the use of this repo. If it is Public Domain, where is this specified? @jlovejoy

**Comment by goneall** [comment]
Some additional information to take into account when drafting an acceptable use or license for this repo.   There are 3 sources of human contribution which results in the data for this repository:

- The original license text (see above for any discussion on the copyright/license for that text)
- The License XML which includes the license text as well as additional metadata.   See [license-list-XML issue #683](https://github.com/spdx/license-list-XML/issues/683) for the current status on the licenses that apply to the schema and metadata.
- The tools that take the license XML and generate the various formats used in the repo.  These are licensed under Apache-2.0 and MIT.

Permissive licenses have been used for all the contributions that I am aware of.

**Comment by goneall** [comment]
With the exception of the README and similar documentation, this repository itself is generated.

It seems that trying to create a "license" for the repository generates some controversy and angst.  Would just stating the facts where this code was generated from and reference the copyright/license information of those sources be sufficient or do we need to create an actual "license" or terms?

**Comment by annania** [comment]
@goneall Thank you for your response. I will discuss with my colleagues and follow up. Thank you!

**Comment by annania** [comment]
@goneall the information you provided and what is written in accessingLicenses.md is sufficient. Thank you!

**Comment by goneall** [comment]
Please review the README file in the licenseinfo branch: https://github.com/spdx/license-list-data/blob/licenseinfo/README.md

I would propose the additional details and information resolves this issue. 

I would appreciate a review and suggested improvements from lawyers in the community.

**Comment by goneall** [comment]
I merged the new README into the repository.  I believe this resolves the issue.
